import {
  ShoppingCart,
  Utensils,
  Dumbbell,
  Gift,
  PiggyBank,
  Ticket,
  BriefcaseBusiness,
  HeartPulse,
  CarFront,
  ToolCase,
  PawPrint,
  House,
  BookOpen,
  BaggageClaim,
  Mailbox,
  ReceiptText,
} from 'lucide-react';

export const iconMap: Record<
  string,
  React.ComponentType<{ className?: string }>
> = {
  business: BriefcaseBusiness,
  car: CarFront,
  heart: HeartPulse,
  bank: PiggyBank,
  shopping: ShoppingCart,
  ticket: Ticket,
  tool: ToolCase,
  utensils: Utensils,
  pet: PawPrint,
  house: House,
  gift: Gift,
  gym: Dumbbell,
  book: BookOpen,
  travel: BaggageClaim,
  mail: Mailbox,
  receipt: ReceiptText,
};
